# -*- coding: utf-8 -*-
"""
Tests for LaTeX compilation pipeline.

Tests:
- MarkdownToLatexConverter
- LatexCompiler document generation
- Template selection
- check_latex_installation utility
"""

import pytest
from pathlib import Path
from unittest.mock import patch, MagicMock

from src.reports.latex_compiler import (
    MarkdownToLatexConverter,
    LatexCompiler,
    LatexConfig,
    check_latex_installation,
    compile_report_to_latex,
    TEMPLATES,
)


# =============================================================================
# MARKDOWN TO LATEX CONVERTER TESTS
# =============================================================================

class TestMarkdownToLatexConverter:
    """Tests for the MarkdownToLatexConverter class."""
    
    @pytest.fixture
    def converter(self):
        return MarkdownToLatexConverter()
    
    def test_convert_header_level_1(self, converter):
        """Test level 1 header conversion."""
        result, _, _ = converter.convert("# Introduction")
        assert "\\section{Introduction}" in result
    
    def test_convert_header_level_2(self, converter):
        """Test level 2 header conversion."""
        result, _, _ = converter.convert("## Methods")
        assert "\\subsection{Methods}" in result
    
    def test_convert_header_level_3(self, converter):
        """Test level 3 header conversion."""
        result, _, _ = converter.convert("### Data Collection")
        assert "\\subsubsection{Data Collection}" in result
    
    def test_convert_bold_text(self, converter):
        """Test bold text conversion."""
        result, _, _ = converter.convert("This is **bold** text.")
        assert "\\textbf{bold}" in result
    
    def test_convert_italic_text(self, converter):
        """Test italic text conversion."""
        result, _, _ = converter.convert("This is *italic* text.")
        assert "\\textit{italic}" in result
    
    def test_convert_code_inline(self, converter):
        """Test inline code conversion."""
        result, _, _ = converter.convert("Use `print()` function.")
        assert "\\texttt{print()}" in result
    
    def test_escape_special_characters(self, converter):
        """Test escaping of LaTeX special characters."""
        result, _, _ = converter.convert("Cost is $100 & 50%")
        assert "\\$" in result
        assert "\\&" in result
        assert "\\%" in result
    
    def test_escape_underscores(self, converter):
        """Test underscore escaping."""
        result, _, _ = converter.convert("variable_name")
        assert "\\_" in result
    
    def test_convert_blockquote(self, converter):
        """Test blockquote conversion."""
        result, _, _ = converter.convert("> This is a note")
        assert "\\begin{quote}" in result
        assert "\\end{quote}" in result
    
    def test_convert_unordered_list_item(self, converter):
        """Test unordered list item conversion."""
        result, _, _ = converter.convert("- First item")
        assert "\\item First item" in result
    
    def test_convert_numbered_list_item(self, converter):
        """Test numbered list item conversion."""
        result, _, _ = converter.convert("1. First item")
        assert "\\item First item" in result
    
    def test_convert_code_block(self, converter):
        """Test code block conversion."""
        markdown = "```\nprint('hello')\n```"
        result, _, _ = converter.convert(markdown)
        assert "\\begin{verbatim}" in result
        assert "\\end{verbatim}" in result
    
    def test_convert_simple_table(self, converter):
        """Test simple table conversion."""
        markdown = """| Name | Value |
|------|-------|
| A    | 1     |
| B    | 2     |"""
        result, _, _ = converter.convert(markdown)
        assert "\\begin{tabular}" in result
        assert "\\end{tabular}" in result
        assert "\\textbf{Name}" in result
        assert "\\hline" in result
    
    def test_skip_horizontal_rule(self, converter):
        """Test that horizontal rules are removed."""
        result, _, _ = converter.convert("---")
        assert "---" not in result
    
    def test_skip_metadata_lines(self, converter):
        """Test that metadata lines are skipped."""
        result, _, _ = converter.convert("*Generated by INQUIRO*")
        assert "Generated" not in result or "\\textit" in result
    
    def test_convert_unicode_characters(self, converter):
        """Test unicode character conversion."""
        result, _, _ = converter.convert("α = β ± ε")
        assert "$\\alpha$" in result
        assert "$\\beta$" in result
        assert "$\\pm$" in result
    
    def test_convert_emoji_to_text(self, converter):
        """Test emoji conversion to text markers."""
        result, _, _ = converter.convert("✅ Success")
        assert "[OK]" in result
        assert "✅" not in result
    
    def test_remove_numbered_section_prefix(self, converter):
        """Test that numbered prefixes in headers are handled."""
        result, _, _ = converter.convert("## 2.1 Methods")
        # The converter may or may not strip the number - verify it at least converts to subsection
        assert "\\subsection" in result
        # The number may be preserved in the title - that's acceptable


# =============================================================================
# LATEX COMPILER TESTS
# =============================================================================

class TestLatexCompiler:
    """Tests for the LatexCompiler class."""
    
    @pytest.fixture
    def compiler(self):
        return LatexCompiler()
    
    @pytest.fixture
    def compiler_with_config(self):
        config = LatexConfig(
            template="arxiv",
            author="Test Author",
            institution="Test University",
        )
        return LatexCompiler(config)
    
    def test_default_config(self, compiler):
        """Test default configuration values."""
        assert compiler.config.template == "plain"
        assert compiler.config.compile_pdf == True
        assert compiler.config.author == "INQUIRO Autonomous Research System"
    
    def test_custom_config(self, compiler_with_config):
        """Test custom configuration."""
        assert compiler_with_config.config.template == "arxiv"
        assert compiler_with_config.config.author == "Test Author"
    
    def test_invalid_template_falls_back(self):
        """Test that invalid template falls back to plain."""
        config = LatexConfig(template="invalid_template")
        assert config.template == "plain"
    
    def test_generate_document_has_title(self, compiler):
        """Test that generated document includes title."""
        doc = compiler._generate_document(
            title="Test Title",
            body="Test body content",
            references=[]
        )
        assert "Test Title" in doc
    
    def test_generate_document_has_author(self, compiler_with_config):
        """Test that generated document includes author."""
        doc = compiler_with_config._generate_document(
            title="Test",
            body="Content",
            references=[]
        )
        assert "Test Author" in doc
    
    def test_generate_document_has_body(self, compiler):
        """Test that generated document includes body."""
        doc = compiler._generate_document(
            title="Test",
            body="This is the main content",
            references=[]
        )
        assert "This is the main content" in doc
    
    def test_generate_bibliography_empty(self, compiler):
        """Test empty bibliography generation."""
        bib = compiler._generate_bibliography([])
        assert bib == ""
    
    def test_generate_bibliography_with_refs(self, compiler):
        """Test bibliography generation with references."""
        refs = [
            {"authors": "Smith et al.", "title": "A Study", "year": "2024", "doi": "10.1234/test"}
        ]
        bib = compiler._generate_bibliography(refs)
        assert "Smith et al." in bib
        assert "A Study" in bib
        assert "2024" in bib
        assert "10.1234/test" in bib
    
    def test_get_builtin_template_plain(self, compiler):
        """Test builtin plain template retrieval."""
        template = compiler._get_builtin_template("plain")
        assert "\\documentclass" in template
        assert "article" in template
        assert "{title}" in template
        assert "{body}" in template
    
    def test_get_builtin_template_arxiv(self, compiler):
        """Test builtin arxiv template retrieval."""
        template = compiler._get_builtin_template("arxiv")
        assert "\\documentclass" in template
        assert "natbib" in template
    
    def test_get_builtin_template_neurips(self, compiler):
        """Test builtin neurips template retrieval."""
        template = compiler._get_builtin_template("neurips")
        assert "neurips" in template.lower()
    
    def test_get_builtin_template_ieee(self, compiler):
        """Test builtin ieee template retrieval."""
        template = compiler._get_builtin_template("ieee")
        assert "IEEEtran" in template
    
    def test_is_latex_available(self, compiler):
        """Test LaTeX availability check."""
        # Just test that the method runs without error
        result = compiler.is_latex_available()
        assert isinstance(result, bool)


# =============================================================================
# LATEX CONFIG TESTS
# =============================================================================

class TestLatexConfig:
    """Tests for LatexConfig dataclass."""
    
    def test_default_values(self):
        """Test default configuration values."""
        config = LatexConfig()
        assert config.template == "plain"
        assert config.compiler == "pdflatex"
        assert config.compile_pdf == True
        assert config.cleanup_aux == True
    
    def test_custom_template(self):
        """Test custom template setting."""
        config = LatexConfig(template="arxiv")
        assert config.template == "arxiv"
    
    def test_invalid_template_fallback(self):
        """Test that invalid template falls back to plain."""
        config = LatexConfig(template="not_a_real_template")
        assert config.template == "plain"
    
    def test_auto_date(self):
        """Test that date is auto-generated if not provided."""
        config = LatexConfig()
        assert config.date != ""
        assert "," in config.date  # Format like "March 09, 2026"


# =============================================================================
# UTILITY FUNCTION TESTS
# =============================================================================

class TestUtilityFunctions:
    """Tests for utility functions."""
    
    def test_check_latex_installation(self):
        """Test check_latex_installation returns dict."""
        result = check_latex_installation()
        assert isinstance(result, dict)
        assert "pdflatex" in result
        assert "xelatex" in result
        assert "lualatex" in result
    
    def test_templates_constant(self):
        """Test TEMPLATES constant contains expected templates."""
        assert "plain" in TEMPLATES
        assert "arxiv" in TEMPLATES
        assert "neurips" in TEMPLATES
        assert "ieee" in TEMPLATES


# =============================================================================
# INTEGRATION TESTS
# =============================================================================

class TestLatexIntegration:
    """Integration tests for LaTeX compilation."""
    
    @pytest.fixture
    def sample_markdown(self):
        return """# Test Report

*Generated by INQUIRO — Autonomous Scientific Research System*

---

## Abstract

This is a test report generated to validate the LaTeX compilation pipeline.

## 1. Introduction

The purpose of this study is to **test** the conversion of markdown to LaTeX.

### 1.1 Background

Previous work by *Smith et al.* demonstrated that testing is important.

## 2. Methods

We used the following approach:

- Step 1: Write markdown
- Step 2: Convert to LaTeX
- Step 3: Compile to PDF

| Method | Result |
|--------|--------|
| Test 1 | Pass   |
| Test 2 | Pass   |

## 3. Results

The conversion was successful. Key findings:

1. Headers convert correctly
2. Tables render properly
3. Lists are preserved

## 4. Conclusion

Testing confirms the LaTeX pipeline works as expected.

## References

1. Smith et al. Testing Methodologies. (2024) DOI: 10.1234/test
"""
    
    def test_full_conversion_pipeline(self, sample_markdown):
        """Test full markdown to LaTeX conversion."""
        converter = MarkdownToLatexConverter()
        latex_body, refs, figs = converter.convert(sample_markdown)
        
        # Check sections converted
        assert "\\section{Abstract}" in latex_body or "Abstract" in latex_body
        assert "\\section{Introduction}" in latex_body or "Introduction" in latex_body
        
        # Check formatting converted
        assert "\\textbf{test}" in latex_body
        
        # Check table converted
        assert "\\begin{tabular}" in latex_body
    
    def test_document_generation(self, sample_markdown):
        """Test full document generation."""
        compiler = LatexCompiler()
        converter = MarkdownToLatexConverter()
        
        body, refs, _ = converter.convert(sample_markdown)
        doc = compiler._generate_document(
            title="Test Report",
            body=body,
            references=refs
        )
        
        # Check document structure
        assert "\\documentclass" in doc
        assert "\\begin{document}" in doc
        assert "\\end{document}" in doc
        assert "\\maketitle" in doc
    
    def test_compile_from_content_creates_tex(self, sample_markdown, tmp_path):
        """Test that compile_from_content creates a .tex file."""
        config = LatexConfig(compile_pdf=False)  # Don't try to compile
        compiler = LatexCompiler(config)
        
        output = compiler.compile_from_content(
            markdown_content=sample_markdown,
            title="Test Report",
            output_dir=str(tmp_path)
        )
        
        assert output is not None
        assert output.endswith(".tex")
        assert Path(output).exists()
        
        # Verify content
        content = Path(output).read_text()
        assert "\\documentclass" in content
        assert "Test Report" in content


# =============================================================================
# EDGE CASE TESTS
# =============================================================================

class TestEdgeCases:
    """Tests for edge cases and error handling."""
    
    @pytest.fixture
    def converter(self):
        return MarkdownToLatexConverter()
    
    def test_empty_markdown(self, converter):
        """Test conversion of empty markdown."""
        result, refs, figs = converter.convert("")
        assert result == ""
        assert refs == []
        assert figs == []
    
    def test_only_whitespace(self, converter):
        """Test conversion of whitespace-only markdown."""
        result, _, _ = converter.convert("   \n\n   ")
        # Should produce empty or whitespace output
        assert result.strip() == ""
    
    def test_nested_formatting(self, converter):
        """Test nested bold/italic formatting."""
        result, _, _ = converter.convert("***bold italic***")
        # Should handle reasonably (exact behavior depends on implementation)
        assert "textbf" in result or "textit" in result
    
    def test_unmatched_formatting(self, converter):
        """Test unmatched formatting markers."""
        result, _, _ = converter.convert("This has *unmatched italic")
        # Should not crash
        assert "unmatched" in result.lower()
    
    def test_very_long_table(self, converter):
        """Test table with many rows."""
        rows = ["| A | B |", "|---|---|"]
        rows.extend([f"| {i} | {i*2} |" for i in range(100)])
        markdown = "\n".join(rows)
        
        result, _, _ = converter.convert(markdown)
        assert "\\begin{tabular}" in result
    
    def test_special_unicode_in_title(self):
        """Test special characters in title."""
        compiler = LatexCompiler()
        doc = compiler._generate_document(
            title="Effect of α-blockers on β-cells",
            body="Test",
            references=[]
        )
        # Should escape properly
        assert "\\documentclass" in doc


# =============================================================================
# RUN TESTS
# =============================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v"])
