# -*- coding: utf-8 -*-
"""
LaTeX Compilation Pipeline for INQUIRO Reports.

Converts Markdown reports to LaTeX and compiles to PDF.
Supports multiple academic templates: NeurIPS, IEEE, arXiv, plain.

Usage:
    compiler = LatexCompiler(template="neurips")
    pdf_path = compiler.compile_report(markdown_path, output_dir)
    
    # Or from content directly:
    pdf_path = compiler.compile_from_content(markdown_content, title, output_dir)
"""

import logging
import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Available templates
TEMPLATES = ["neurips", "ieee", "arxiv", "plain"]
DEFAULT_TEMPLATE = "plain"


@dataclass
class LatexConfig:
    """Configuration for LaTeX compilation."""
    template: str = "plain"
    compiler: str = "pdflatex"  # pdflatex, xelatex, lualatex
    bibliography_style: str = "plain"
    include_toc: bool = False
    include_figures: bool = True
    author: str = "INQUIRO Autonomous Research System"
    institution: str = ""
    date: str = ""
    compile_pdf: bool = True  # If False, only generate .tex file
    cleanup_aux: bool = True  # Remove auxiliary files after compilation
    
    def __post_init__(self):
        if self.template not in TEMPLATES:
            logger.warning(f"Unknown template '{self.template}', using '{DEFAULT_TEMPLATE}'")
            self.template = DEFAULT_TEMPLATE
        if not self.date:
            self.date = datetime.now().strftime("%B %d, %Y")


class MarkdownToLatexConverter:
    """
    Converts INQUIRO Markdown reports to LaTeX format.
    
    Handles:
    - Section headers (# ## ###)
    - Bold/italic text
    - Tables
    - Code blocks
    - Lists
    - Citations and references
    - Figure references
    """
    
    def __init__(self):
        self.references: List[Dict] = []
        self.figures: List[Dict] = []
        self._ref_counter = 0
    
    def convert(self, markdown: str) -> Tuple[str, List[Dict], List[Dict]]:
        """
        Convert markdown content to LaTeX.
        
        Returns:
            Tuple of (latex_body, references, figures)
        """
        self.references = []
        self.figures = []
        self._ref_counter = 0
        
        # Process sections
        lines = markdown.split('\n')
        latex_lines = []
        in_table = False
        in_code_block = False
        table_lines = []
        
        for line in lines:
            # Handle code blocks
            if line.strip().startswith('```'):
                if in_code_block:
                    latex_lines.append('\\end{verbatim}')
                    in_code_block = False
                else:
                    latex_lines.append('\\begin{verbatim}')
                    in_code_block = True
                continue
            
            if in_code_block:
                latex_lines.append(line)
                continue
            
            # Handle tables
            if '|' in line and not line.strip().startswith('>'):
                if not in_table:
                    in_table = True
                    table_lines = []
                table_lines.append(line)
                continue
            elif in_table:
                # End of table
                latex_table = self._convert_table(table_lines)
                latex_lines.extend(latex_table)
                in_table = False
                table_lines = []
            
            # Convert the line
            converted = self._convert_line(line)
            if converted is not None:
                latex_lines.append(converted)
        
        # Close any open table
        if in_table:
            latex_table = self._convert_table(table_lines)
            latex_lines.extend(latex_table)
        
        return '\n'.join(latex_lines), self.references, self.figures

    def _convert_line(self, line: str) -> Optional[str]:
        """Convert a single markdown line to LaTeX."""
        stripped = line.strip()
        
        # Skip metadata lines (Generated by, etc.)
        if stripped.startswith('*Generated by') or stripped.startswith('**Generated:'):
            return None
        
        # Skip horizontal rules
        if stripped == '---':
            return ''
        
        # Handle blockquotes (notes/warnings)
        if stripped.startswith('>'):
            content = stripped[1:].strip()
            content = self._escape_latex(content)
            content = self._convert_inline_formatting(content)
            return f'\\begin{{quote}}\n{content}\n\\end{{quote}}'
        
        # Handle headers
        if stripped.startswith('#'):
            return self._convert_header(stripped)
        
        # Handle list items
        if stripped.startswith('- ') or stripped.startswith('* '):
            content = stripped[2:]
            content = self._escape_latex(content)
            content = self._convert_inline_formatting(content)
            return f'\\item {content}'
        
        # Handle numbered lists
        if re.match(r'^\d+\.\s', stripped):
            content = re.sub(r'^\d+\.\s', '', stripped)
            content = self._escape_latex(content)
            content = self._convert_inline_formatting(content)
            return f'\\item {content}'
        
        # Regular paragraph
        if stripped:
            content = self._escape_latex(stripped)
            content = self._convert_inline_formatting(content)
            return content
        
        return ''
    
    def _convert_header(self, line: str) -> str:
        """Convert markdown header to LaTeX section."""
        match = re.match(r'^(#{1,4})\s*(.+)$', line)
        if not match:
            return self._escape_latex(line)
        
        level = len(match.group(1))
        title = match.group(2).strip()
        
        # Remove numbering if present (e.g., "1. Introduction" -> "Introduction")
        title = re.sub(r'^\d+\.\s*', '', title)
        title = self._escape_latex(title)
        
        section_cmds = {
            1: 'section',
            2: 'subsection',
            3: 'subsubsection',
            4: 'paragraph'
        }
        
        cmd = section_cmds.get(level, 'paragraph')
        return f'\\{cmd}{{{title}}}'

    def _convert_table(self, lines: List[str]) -> List[str]:
        """Convert markdown table to LaTeX tabular."""
        if len(lines) < 2:
            return []
        
        # Parse header row
        header = [cell.strip() for cell in lines[0].split('|') if cell.strip()]
        num_cols = len(header)
        
        if num_cols == 0:
            return []
        
        # Build LaTeX table
        result = []
        col_spec = '|' + 'l|' * num_cols
        result.append('\\begin{table}[h]')
        result.append('\\centering')
        result.append(f'\\begin{{tabular}}{{{col_spec}}}')
        result.append('\\hline')
        
        # Header row (bold)
        header_cells = [f'\\textbf{{{self._escape_latex(h)}}}' for h in header]
        result.append(' & '.join(header_cells) + ' \\\\')
        result.append('\\hline')
        
        # Data rows (skip separator row)
        for line in lines[2:]:  # Skip header and separator
            if not line.strip() or line.strip().startswith('|--'):
                continue
            cells = [cell.strip() for cell in line.split('|') if cell.strip()]
            if len(cells) == num_cols:
                escaped = [self._escape_latex(c) for c in cells]
                # Convert inline formatting in cells
                escaped = [self._convert_inline_formatting(c) for c in escaped]
                result.append(' & '.join(escaped) + ' \\\\')
        
        result.append('\\hline')
        result.append('\\end{tabular}')
        result.append('\\end{table}')
        result.append('')
        
        return result
    
    def _escape_latex(self, text: str) -> str:
        """Escape special LaTeX characters."""
        # Order matters - escape backslash first
        replacements = [
            ('\\', '\\textbackslash{}'),
            ('&', '\\&'),
            ('%', '\\%'),
            ('$', '\\$'),
            ('#', '\\#'),
            ('_', '\\_'),
            ('{', '\\{'),
            ('}', '\\}'),
            ('~', '\\textasciitilde{}'),
            ('^', '\\textasciicircum{}'),
        ]
        
        for old, new in replacements:
            text = text.replace(old, new)
        
        # Handle special unicode characters
        text = text.replace('—', '---')
        text = text.replace('–', '--')
        text = text.replace(''', "'")
        text = text.replace(''', "'")
        text = text.replace('"', "``")
        text = text.replace('"', "''")
        text = text.replace('…', '...')
        text = text.replace('≤', '$\\leq$')
        text = text.replace('≥', '$\\geq$')
        text = text.replace('±', '$\\pm$')
        text = text.replace('×', '$\\times$')
        text = text.replace('α', '$\\alpha$')
        text = text.replace('β', '$\\beta$')
        text = text.replace('ε', '$\\epsilon$')
        
        return text

    def _convert_inline_formatting(self, text: str) -> str:
        """Convert markdown inline formatting to LaTeX."""
        # Bold: **text** or __text__ -> \textbf{text}
        text = re.sub(r'\*\*(.+?)\*\*', r'\\textbf{\1}', text)
        text = re.sub(r'__(.+?)__', r'\\textbf{\1}', text)
        
        # Italic: *text* or _text_ -> \textit{text}
        text = re.sub(r'\*([^*]+?)\*', r'\\textit{\1}', text)
        text = re.sub(r'_([^_]+?)_', r'\\textit{\1}', text)
        
        # Code: `text` -> \texttt{text}
        text = re.sub(r'`([^`]+?)`', r'\\texttt{\1}', text)
        
        # Handle emojis (remove or convert)
        emoji_map = {
            '📚': '[Lit]',
            '📊': '[Data]',
            '✅': '[OK]',
            '❌': '[X]',
            '⚠️': '[!]',
            '🔴': '[H]',
            '🟡': '[M]',
            '🟢': '[L]',
            '🔬': '',
            '🎯': '',
            '📝': '',
            '💾': '',
        }
        for emoji, replacement in emoji_map.items():
            text = text.replace(emoji, replacement)
        
        return text


class LatexCompiler:
    """
    Compiles INQUIRO reports to LaTeX and PDF.
    
    Supports templates:
    - neurips: NeurIPS conference format
    - ieee: IEEE journal format
    - arxiv: arXiv preprint format
    - plain: Simple article class
    """
    
    def __init__(self, config: Optional[LatexConfig] = None):
        self.config = config or LatexConfig()
        self.converter = MarkdownToLatexConverter()
        self._template_dir = Path(__file__).parent / "templates"
    
    def compile_report(
        self,
        markdown_path: str,
        output_dir: str,
        title: Optional[str] = None
    ) -> Optional[str]:
        """
        Compile a markdown report to PDF.
        
        Args:
            markdown_path: Path to the markdown report file
            output_dir: Directory for output files
            title: Optional title override
            
        Returns:
            Path to compiled PDF, or path to .tex if compilation failed
        """
        md_path = Path(markdown_path)
        if not md_path.exists():
            logger.error(f"Markdown file not found: {markdown_path}")
            return None
        
        markdown_content = md_path.read_text(encoding='utf-8')
        
        # Extract title from first line if not provided
        if not title:
            first_line = markdown_content.split('\n')[0]
            if first_line.startswith('#'):
                title = first_line.lstrip('#').strip()
            else:
                title = md_path.stem
        
        return self.compile_from_content(markdown_content, title, output_dir)

    def compile_from_content(
        self,
        markdown_content: str,
        title: str,
        output_dir: str
    ) -> Optional[str]:
        """
        Compile markdown content to PDF.
        
        Args:
            markdown_content: Markdown text content
            title: Document title
            output_dir: Directory for output files
            
        Returns:
            Path to compiled PDF or .tex file
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # Convert markdown to LaTeX body
        latex_body, references, figures = self.converter.convert(markdown_content)
        
        # Generate full LaTeX document
        latex_doc = self._generate_document(title, latex_body, references)
        
        # Save .tex file
        safe_title = re.sub(r'[^\w\s-]', '', title)[:40].strip().replace(' ', '_')
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        tex_filename = f"report_{safe_title}_{timestamp}.tex"
        tex_path = output_path / tex_filename
        
        tex_path.write_text(latex_doc, encoding='utf-8')
        logger.info(f"LaTeX source saved: {tex_path}")
        
        # Compile to PDF if requested
        if self.config.compile_pdf:
            pdf_path = self._compile_to_pdf(tex_path)
            if pdf_path:
                return str(pdf_path)
        
        return str(tex_path)
    
    def _generate_document(
        self,
        title: str,
        body: str,
        references: List[Dict]
    ) -> str:
        """Generate complete LaTeX document from template."""
        template = self._get_template()
        
        # Escape title for LaTeX
        safe_title = self.converter._escape_latex(title)
        
        # Generate bibliography
        bibliography = self._generate_bibliography(references)
        
        # Fill template
        doc = template.format(
            title=safe_title,
            author=self.config.author,
            institution=self.config.institution,
            date=self.config.date,
            body=body,
            bibliography=bibliography
        )
        
        return doc
    
    def _get_template(self) -> str:
        """Get the LaTeX template for the configured style."""
        template_file = self._template_dir / f"{self.config.template}.tex"
        
        if template_file.exists():
            return template_file.read_text(encoding='utf-8')
        
        # Fallback to built-in templates
        logger.info(f"Using built-in {self.config.template} template")
        return self._get_builtin_template(self.config.template)

    def _get_builtin_template(self, template_name: str) -> str:
        """Get built-in LaTeX template."""
        templates = {
            "plain": r"""\documentclass[11pt,a4paper]{{article}}
\usepackage[utf8]{{inputenc}}
\usepackage[T1]{{fontenc}}
\usepackage{{amsmath,amssymb}}
\usepackage{{graphicx}}
\usepackage{{hyperref}}
\usepackage{{booktabs}}
\usepackage{{geometry}}
\geometry{{margin=1in}}

\title{{{title}}}
\author{{{author}}}
\date{{{date}}}

\begin{{document}}
\maketitle

{body}

{bibliography}

\end{{document}}
""",
            "arxiv": r"""\documentclass[11pt]{{article}}
\usepackage[utf8]{{inputenc}}
\usepackage[T1]{{fontenc}}
\usepackage{{amsmath,amssymb,amsfonts}}
\usepackage{{graphicx}}
\usepackage{{hyperref}}
\usepackage{{booktabs}}
\usepackage{{natbib}}
\usepackage[margin=1in]{{geometry}}

\title{{{title}}}
\author{{{author} \\ {institution}}}
\date{{{date}}}

\begin{{document}}
\maketitle

\begin{{abstract}}
% Abstract will be extracted from body
\end{{abstract}}

{body}

{bibliography}

\end{{document}}
""",
            "neurips": r"""\documentclass{{article}}
\usepackage[final]{{neurips_2024}}
\usepackage[utf8]{{inputenc}}
\usepackage[T1]{{fontenc}}
\usepackage{{amsmath,amssymb}}
\usepackage{{graphicx}}
\usepackage{{hyperref}}
\usepackage{{booktabs}}

\title{{{title}}}
\author{{{author}}}

\begin{{document}}
\maketitle

{body}

{bibliography}

\end{{document}}
""",
            "ieee": r"""\documentclass[conference]{{IEEEtran}}
\usepackage[utf8]{{inputenc}}
\usepackage[T1]{{fontenc}}
\usepackage{{amsmath,amssymb}}
\usepackage{{graphicx}}
\usepackage{{hyperref}}
\usepackage{{booktabs}}
\usepackage{{cite}}

\title{{{title}}}
\author{{{author}}}

\begin{{document}}
\maketitle

{body}

{bibliography}

\end{{document}}
"""
        }
        return templates.get(template_name, templates["plain"])

    def _generate_bibliography(self, references: List[Dict]) -> str:
        """Generate LaTeX bibliography section."""
        if not references:
            return ""
        
        lines = [
            "\\section*{References}",
            "\\begin{enumerate}"
        ]
        
        for ref in references:
            # Format reference entry
            authors = ref.get('authors', 'Unknown')
            title = ref.get('title', 'Untitled')
            year = ref.get('year', '')
            source = ref.get('source', '')
            doi = ref.get('doi', '')
            
            entry = f"\\item {authors}. \\textit{{{title}}}."
            if year:
                entry += f" ({year})."
            if source:
                entry += f" {source}."
            if doi:
                entry += f" DOI: {doi}"
            
            lines.append(entry)
        
        lines.append("\\end{enumerate}")
        return '\n'.join(lines)
    
    def _compile_to_pdf(self, tex_path: Path) -> Optional[Path]:
        """
        Compile LaTeX file to PDF using pdflatex.
        
        Returns:
            Path to PDF if successful, None otherwise
        """
        # Check if LaTeX compiler is available
        compiler = self._find_latex_compiler()
        if not compiler:
            logger.warning(
                "No LaTeX compiler found. Install TeX Live, MiKTeX, or MacTeX. "
                "Returning .tex file only."
            )
            return None
        
        logger.info(f"Compiling with {compiler}...")
        
        # Run compiler (twice for references)
        work_dir = tex_path.parent
        tex_name = tex_path.name
        
        try:
            for run in range(2):  # Two passes for references
                result = subprocess.run(
                    [compiler, "-interaction=nonstopmode", tex_name],
                    cwd=str(work_dir),
                    capture_output=True,
                    text=True,
                    timeout=120
                )
                
                if result.returncode != 0 and run == 1:
                    logger.warning(f"LaTeX compilation warning (may be non-fatal)")
                    logger.debug(f"LaTeX output: {result.stdout[-500:]}")
            
            # Check for PDF
            pdf_path = tex_path.with_suffix('.pdf')
            if pdf_path.exists():
                logger.info(f"PDF compiled successfully: {pdf_path}")
                
                # Cleanup auxiliary files
                if self.config.cleanup_aux:
                    self._cleanup_aux_files(tex_path)
                
                return pdf_path
            else:
                logger.error("PDF not generated - check LaTeX errors")
                # Log last part of output for debugging
                if result.stdout:
                    logger.debug(f"Compiler output: {result.stdout[-1000:]}")
                return None
                
        except subprocess.TimeoutExpired:
            logger.error("LaTeX compilation timed out")
            return None
        except Exception as e:
            logger.error(f"LaTeX compilation failed: {e}")
            return None

    def _find_latex_compiler(self) -> Optional[str]:
        """Find an available LaTeX compiler."""
        compilers = [self.config.compiler, 'pdflatex', 'xelatex', 'lualatex']
        
        for compiler in compilers:
            if shutil.which(compiler):
                return compiler
        
        return None
    
    def _cleanup_aux_files(self, tex_path: Path) -> None:
        """Remove auxiliary files generated by LaTeX."""
        aux_extensions = ['.aux', '.log', '.out', '.toc', '.lof', '.lot', 
                         '.bbl', '.blg', '.nav', '.snm', '.vrb']
        
        for ext in aux_extensions:
            aux_file = tex_path.with_suffix(ext)
            if aux_file.exists():
                try:
                    aux_file.unlink()
                except Exception:
                    pass
    
    def is_latex_available(self) -> bool:
        """Check if LaTeX compilation is available."""
        return self._find_latex_compiler() is not None


def compile_report_to_latex(
    markdown_path: str,
    output_dir: str,
    template: str = "plain",
    compile_pdf: bool = True,
    author: str = "INQUIRO Autonomous Research System"
) -> Optional[str]:
    """
    Convenience function to compile a INQUIRO report to LaTeX/PDF.
    
    Args:
        markdown_path: Path to the markdown report
        output_dir: Directory for output files
        template: LaTeX template ("plain", "arxiv", "neurips", "ieee")
        compile_pdf: Whether to compile to PDF (requires LaTeX installed)
        author: Author name for the document
        
    Returns:
        Path to the compiled PDF or .tex file
        
    Example:
        >>> pdf_path = compile_report_to_latex(
        ...     "outputs/run_xxx/report.md",
        ...     "outputs/run_xxx/latex",
        ...     template="arxiv"
        ... )
    """
    config = LatexConfig(
        template=template,
        compile_pdf=compile_pdf,
        author=author
    )
    compiler = LatexCompiler(config)
    return compiler.compile_report(markdown_path, output_dir)


def check_latex_installation() -> Dict[str, bool]:
    """
    Check which LaTeX compilers are available.
    
    Returns:
        Dict mapping compiler names to availability
        
    Example:
        >>> check_latex_installation()
        {'pdflatex': True, 'xelatex': True, 'lualatex': False}
    """
    compilers = ['pdflatex', 'xelatex', 'lualatex']
    return {c: shutil.which(c) is not None for c in compilers}
